services:
  # Main API Service
  - type: web
    name: youtube-shorts-api
    env: docker
    region: oregon
    plan: starter
    dockerfilePath: ./Dockerfile
    dockerContext: .
    healthCheckPath: /api/v1/health
    
    # Auto-deploy settings
    autoDeploy: false

